version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  

